apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: natsusers.nats.deinstapel.de
  annotations:
    controller-gen.kubebuilder.io/version: v0.11.1
  labels:
  {{- include "nats-jwt-operator.labels" . | nindent 4 }}
spec:
  group: nats.deinstapel.de
  names:
    kind: NatsUser
    listKind: NatsUserList
    plural: natsusers
    singular: natsuser
  scope: Namespaced
  versions:
  - name: v1alpha1
    schema:
      openAPIV3Schema:
        description: NatsUser is the Schema for the natsusers API
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            description: NatsUserSpec defines the desired state of NatsUser
            properties:
              accountRef:
                description: AccountRef is the reference to the account that should
                  sign this user
                properties:
                  apiVersion:
                    description: API version of the referent.
                    type: string
                  fieldPath:
                    description: 'If referring to a piece of an object instead of an
                      entire object, this string should contain a valid JSON/Go field
                      access statement, such as desiredState.manifest.containers[2].
                      For example, if the object reference is to a container within
                      a pod, this would take on a value like: "spec.containers{name}"
                      (where "name" refers to the name of the container that triggered
                      the event) or if no container name is specified "spec.containers[2]"
                      (container with index 2 in this pod). This syntax is chosen only
                      to have some well-defined way of referencing a part of an object.
                      TODO: this design is not final and this field is subject to change
                      in the future.'
                    type: string
                  kind:
                    description: 'Kind of the referent. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
                    type: string
                  name:
                    description: 'Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names'
                    type: string
                  namespace:
                    description: 'Namespace of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/namespaces/'
                    type: string
                  resourceVersion:
                    description: 'Specific resourceVersion to which this reference is
                      made, if any. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#concurrency-control-and-consistency'
                    type: string
                  uid:
                    description: 'UID of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#uids'
                    type: string
                type: object
                x-kubernetes-map-type: atomic
              allowed_connection_types:
                description: StringList is a wrapper for an array of strings
                items:
                  type: string
                type: array
              bearer_token:
                type: boolean
              limits:
                properties:
                  data:
                    format: int64
                    type: integer
                  payload:
                    format: int64
                    type: integer
                  src:
                    description: TagList is a unique array of lower case strings All
                      tag list methods lower case the strings in the arguments
                    items:
                      type: string
                    type: array
                  subs:
                    format: int64
                    type: integer
                  times:
                    items:
                      description: TimeRange is used to represent a start and end time
                      properties:
                        end:
                          type: string
                        start:
                          type: string
                      type: object
                    type: array
                  times_location:
                    type: string
                type: object
              permissions:
                description: Copied from nats-io/jwt to get codegen
                properties:
                  pub:
                    properties:
                      allow:
                        description: StringList is a wrapper for an array of strings
                        items:
                          type: string
                        type: array
                      deny:
                        description: StringList is a wrapper for an array of strings
                        items:
                          type: string
                        type: array
                    type: object
                  resp:
                    description: ResponsePermission can be used to allow responses to
                      any reply subject that is received on a valid subscription.
                    properties:
                      max:
                        type: integer
                      ttl:
                        description: A Duration represents the elapsed time between
                          two instants as an int64 nanosecond count. The representation
                          limits the largest representable duration to approximately
                          290 years.
                        format: int64
                        type: integer
                    required:
                    - max
                    - ttl
                    type: object
                  sub:
                    properties:
                      allow:
                        description: StringList is a wrapper for an array of strings
                        items:
                          type: string
                        type: array
                      deny:
                        description: StringList is a wrapper for an array of strings
                        items:
                          type: string
                        type: array
                    type: object
                type: object
            required:
            - accountRef
            type: object
          status:
            description: NatsUserStatus defines the observed state of NatsUser
            properties:
              jwt:
                type: string
              publicKey:
                type: string
              userSecretName:
                type: string
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []